name: CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  # The job running the package tests.
  test:
    name: ${{ matrix.gap-branch }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        gap-branch:
          - master
          - stable-4.11
          - stable-4.10

    steps:
      - uses: actions/checkout@v2
      - uses: gap-actions/setup-gap@v2
        with:
          GAPBRANCH: ${{ matrix.gap-branch }}
      - uses: gap-actions/build-pkg-docs@v1
      - uses: gap-actions/build-pkg@v1
      - uses: gap-actions/run-pkg-tests@v2
      - uses: gap-actions/process-coverage@v2
      - uses: codecov/codecov-action@v2

  # A job to compile the manual with latex and upload it as an artifact.
  manual:
    name: Build manuals
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gap-actions/setup-gap@v2
      - uses: gap-actions/build-pkg-docs@v1
        with:
          use-latex: 'true'
      - name: "Upload documentation"
        uses: actions/upload-artifact@v2
        with:
          name: manual
          path: ./doc/manual.pdf
